export const ADD_TODO = "ADD_TODO"
export const COMPLETED_TASK = "COMPLETED_TASK"
export const SEARCH_HASH = "SEARCH_HASH"
export const TOGGLE_TASK = "TOGGLE_TASK"
export const CLEAR_ALL = "CLEAR_ALL"
